---
version: "3"

tasks:
  fmt:
    cmds:
      - ruff format
      - prettier --write .
  lint:
    cmds:
      - ruff check
      - prettier --check .
      - actionlint .github/workflows/*.yml
  test:
    cmds:
      - ./venv/bin/python -m unittest discover -p "test_*.py"
